from ib_insync import *
from src.utils.logger import logger
from src.components.connection_manager import ConnectionManager

class OrderManager:
    """Handles order submission and position management via IBKR."""

    def __init__(self, conn: ConnectionManager):
        self.conn = conn
        self.ib = conn.ib

    # ------------------------------------------------------------------
    # Order placement
    # ------------------------------------------------------------------
    def place_order(self, strategy, orders):
        """Place orders generated by a strategy.
        Parameters
        ----------
        strategy : Strategy instance that produced the order, required to locate
                    contract information (using `strategy.params.get_mes_data`).
        orders : Iterable[ib_insync.Order]
        """
        logger.info(f"Placing order(s): {orders}")
        if not self.conn.is_connected():
            logger.warning("No connection when placing order. Attempting reconnection…")
            if not self.conn.reconnect():
                raise Exception("Cannot place order - no connection to IBKR")

        async def _place():
            mes_data = strategy.params.get_mes_data()
            if not mes_data:
                logger.error("No MES contract data found for order placement")
                return False
            contract = mes_data.contract
            self.ib.qualifyContracts(contract)
            for o in orders:
                logger.debug(f"Submitting order: {o}")
                self.ib.placeOrder(contract, o)
            return True

        try:
            self.conn._execute(_place())
            logger.success("Order(s) submitted to IBKR.")
            return True
        except Exception as e:
            logger.error(f"Error placing order: {str(e)}")
            raise

    # ------------------------------------------------------------------
    # Close all positions / cancel orders
    # ------------------------------------------------------------------
    def close_all_positions(self):
        logger.info("Closing all positions…")
        if not self.conn.is_connected():
            logger.warning("No connection when closing positions. Attempting reconnection…")
            if not self.conn.reconnect():
                raise Exception("Cannot close positions - no connection to IBKR")

        async def _close():
            for order in self.ib.orders():
                self.ib.cancelOrder(order)
            logger.success("Successfully closed all positions")
            return True

        try:
            self.conn._execute(_close())
            return True
        except Exception as e:
            logger.error(f"Error closing all positions: {str(e)}")
            raise
